### ISSUE TITLE
Nie działała w niedzielę transmisja BVB - Augsburg

### ISSUE THREAD

**Issue by kisiel999** [Mariusz89B/plugin.video.viaplay#10]
Błąd podczas transmisji BVB - Augsburg we wtyczce Viaplay, w logu sypie errorem 404. Ktoś miał kiedyś error chyba podczas transmisji z Premier League również. https://justpaste.it/7wkmj

**Comment by Mariusz89B** [comment]
Poprawka w v2.4.0
https://github.com/Mariusz89B/plugin.video.viaplay/releases/tag/v2.4.0

https://github.com/Mariusz89B/plugin.video.viaplay/commit/15d933debf608fa6678c49c35f7fe8ce3b6bf1ac
