### ISSUE TITLE
No subtitle on any content

### ISSUE THREAD

**Issue by ZebMcKayhan** [Mariusz89B/plugin.video.viaplay#12]
Hello and thanks for a great addon!

We recently started a subscription so I installed this addon to my rpi4 running libreElec 10.0.4. All content plays perfect and I can select audio tracks if I want. But there are no subtitles and if I try to select one it is greyed out, so there are none to select.

My prefered subtilte language is swedish in kodi settings. Subtitles works for other streaming apps, like SVTPlay.

There are no obvious errors in kodi log regarding subtitles, but I have not enabled debug logging yet.

Subtitles are enabled in the Viaplay-settings.

Am I the only one with this issue? Is there some settings I have missed?

Log file: https://pastebin.com/QFDgxCPS

**Comment by mostman** [comment]
Have the same issue, subtitles vanished at some point for the viaplay plugin, not sure when.

**Comment by ZebMcKayhan** [comment]
I turned on debug logging in kodi. I tried to quickly open viaplay and play a movie I know should have subtitles for a minute then turned off but it still created an over 2MB log file:
https://paste.c-net.org/CrueltyHandgun

A quick search for 'subtitle' gives:
`2023-02-05 20:00:51.260 T:1065    DEBUG <CSettingsManager>: requested setting (subtitles.enable) was not found.
2023-02-05 20:00:51.260 T:1065    DEBUG <CSettingsManager>: requested setting (subtitles.delay) was not found.
2023-02-05 20:00:51.260 T:1065    DEBUG <CSettingsManager>: requested setting (subtitles.stream) was not found.
2023-02-05 20:00:51.260 T:1065    DEBUG <CSettingsManager>: requested setting (subtitles.browser) was not found.
2023-02-05 20:00:51.260 T:1065    DEBUG <CSettingsManager>: requested setting (subtitles.search) was not found.
2023-02-05 20:00:51.260 T:1065    DEBUG <CSettingsManager>: requested setting (audio.makedefault) was not found.`

**Comment by mostman** [comment]
Hi i am running kodi 19.5 under Slackware ARM. Hardware is a Rasberry Pi 4.
I think there has been som changes in Viaplays api handling "subtitles" as i have the same issue.
As you log stats there CSettingsManager cant find requested setting subtitles.stream

**Comment by ZebMcKayhan** [comment]
@mostman and whoever else is reading this, I installed
https://github.com/zuzia-dev/kodi-viaplay
Instead and the subtitles works and everything else I tried... also with a bonus of supporting change of profiles which is nice.

Not sure whether I should close this issue report as MY issue is resolved but the issue remains in this repo/release. Ill leave it open for visibility sake.

**Comment by Mariusz89B** [comment]
Hi, sorry for late response. Please check if this version is working.
https://github.com/Mariusz89B/plugin.video.viaplay/releases/tag/v2.4.0_v1

**Comment by ZebMcKayhan** [comment]
Thanks @Mariusz89B subtitles seems to be working on your 2.4.0 beta1. I did not check the logs, but tested both movies and episodes and its working.

**Comment by Mariusz89B** [comment]
Thank you for testing it out, I made a mistake in v2.3.9 release.

**Comment by Mariusz89B** [comment]
Fixed in v2.4.0
https://github.com/Mariusz89B/plugin.video.viaplay/releases/tag/v2.4.0

https://github.com/Mariusz89B/plugin.video.viaplay/commit/15d933debf608fa6678c49c35f7fe8ce3b6bf1ac
