### ISSUE TITLE
Search returns "Viaplay Error" (SE)

### ISSUE THREAD

**Issue by ZebMcKayhan** [Mariusz89B/plugin.video.viaplay#13]
Hello

Running Viaplay (se domain) 2.4.0 on rpi4b matrix 19.5 I can enter the search dialogue, but whenever I enter my search term and hit "search" it exits the dialogue with "Viaplay Error - Check the log for more info".

I made a quick log snip for the time when the error uccrued. I will generate more comprehensive logs if needed:
https://paste.c-net.org/SewersRugged

/Zeb

**Comment by Mariusz89B** [comment]
@ZebMcKayhan Viaplay made some changes requiring headers to be used in the request session, please see if version 2.4.1-beta.2 is working out for you.
https://github.com/Mariusz89B/plugin.video.viaplay/releases/tag/2.4.1_v2

https://github.com/Mariusz89B/plugin.video.viaplay/commit/c1d50f488afdded756f2438c862bb09308e44259

**Comment by ZebMcKayhan** [comment]
Thank you @Mariusz89B I will test as soon as I get back home, which is after the weekend.

**Comment by ZebMcKayhan** [comment]
@Mariusz89B I managed to squeeze in a quick test before Im leaving home and it is working! 

Thank you!

**Comment by Mariusz89B** [comment]
@ZebMcKayhan Yes, but I now see that I may have broken other categories. I will send out a patch later in the evening.

**Comment by Mariusz89B** [comment]
Fixed my mistake in 2.4.1_v3
https://github.com/Mariusz89B/plugin.video.viaplay/releases/tag/2.4.1_v3

https://github.com/Mariusz89B/plugin.video.viaplay/commit/8d8acf6f95510eb1efcab3c1aca2264f6d7e471f

**Comment by ZebMcKayhan** [comment]
Sorry for the late reply. Ive been away until now.

Ive installed the 2.4.1.beta 5 and been trying everything I could think of and it works! 

Thank you very much and Great job!
