### ISSUE TITLE
2.4.1-beta.4 Plays incorrect choise

### ISSUE THREAD

**Issue by mostman** [Mariusz89B/plugin.video.viaplay#14]
When trying to choose a movie/program from playlist, it always plays the first movie in the list.
Subtitles seams to work now, and search also seams to work...so that seams to be fixed.
Problem seams to be that no matter what movie/program you choose, it always plays the first option in the list.

Tried 2.4.1-beta3
Search works fine, Subtitles works fine and choosing movie/program from list works fine.
So seams you maybe broke something in 2.4.1-beta4?

**Comment by Mariusz89B** [comment]
I can't replicate this issue, all series are just playing fine, could you provide a log file?
