### ISSUE TITLE
Brak skrótów we wtyczce Viaplay w KODI

### ISSUE THREAD

**Issue by kisiel999** [Mariusz89B/plugin.video.viaplay#16]
Takie coś jest na stronie Viaplay, a we wtyczce nie.
![Screenshot 2023-02-26 at 19-35-13 Odtwarzaj strumieniowo sport na żywo online - Odtwarzaj strumieniowo sport online](https://user-images.githubusercontent.com/49946524/221429783-a388afde-3fb1-4345-9f39-6010a907bf62.png)

**Comment by DenDyGH** [comment]
Przecież są skróty w dziale Sport > Najlepsze skróty meczów
