### ISSUE TITLE
Problemy z odtwarzaniem transmisji

### ISSUE THREAD

**Issue by kisiel999** [Mariusz89B/plugin.video.viaplay#17]
Kiedyś (po aktualizacji) Everton - Arsenal:
https://justpaste.it/amk6t

Na Lechu miałem jeszcze desynchronizację dźwięku z obrazem:

Uruchamiało, ale na Lechu coś z dźwiękiem było nie tak i stawał obraz (zobaczę w logu). W przeglądarce chodziło jak trzeba.

2023-02-16 18:52:08.067 T:6220  warning <general>: ActiveAE - large audio sync error: -10190.252304

Takich miałem dużo komunikatów w logu, jak włączyłem Lecha.

**Comment by Mariusz89B** [comment]
Problem nie dotyczy wtyczki tylko inputstream.adaptive.

`AddOnLog: inputstream.adaptive: Download failed with error 404`
