### ISSUE TITLE
Viaplay sweden

### ISSUE THREAD

**Issue by Mr-Deadbeat** [Mariusz89B/plugin.video.viaplay#19]
tested out v2.4.5 last night and as far as i could tell everything else works except channels can't watch live tv streams it crashes or i get an error message

running kodi 11.0.0.1 Libreelec

**Comment by praspp** [comment]
Install the latest pre-release:
https://github.com/Mariusz89B/plugin.video.viaplay/releases/tag/v2.4.6_v2

**Comment by Mr-Deadbeat** [comment]
> @Mr-Deadbeat Install the latest pre-release: https://github.com/Mariusz89B/plugin.video.viaplay/releases/tag/v2.4.6_v2

thanks i will check it out i appreciate the help :)

**Comment by Mr-Deadbeat** [comment]
i got it working with the version suggested so closing the issue
